### ISSUE TITLE
nosetests fail, LatticeThermodynamics not found 

### ISSUE THREAD

**Issue by volkansevim** [harmslab/latticeproteins#6]
Hi Zach,

I'm trying to install the latest commit, b2add37. Five of the nosetests fail. Here's a few lines from the output:

```
EEEE......E
======================================================================
ERROR: test__init__ (latticeproteins.tests.test_conformations.TestConformationList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/u2/v/vsevim/software/latticeproteins/latticeproteins/tests/test_conformations.py", line 75, in test__init__
    c = ConformationList(self.length, self.confs)
  File "/global/u2/v/vsevim/software/latticeproteins/latticeproteins/conformations.py", line 573, in __init__
    self._length = len(self._conflist[0]) + 1
TypeError: 'int' object is not subscriptable
```
Also this line in the notebook fails with the following error:
`lattice = lp.LatticeThermodynamics.from_length(seq_length, 1.0)
`
```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-59950d236e64> in <module>
      1 seq_length = 10
      2 temperature = 1.0
----> 3 lattice = lp.LatticeThermodynamics.from_length(seq_length, 1.0)

AttributeError: module 'latticeproteins' has no attribute 'LatticeThermodynamics' 
```

Could you help me out?

**Comment by hockeyDavid800** [comment]
I'm also having trouble with python not recognizing latticethermodynamics.
